---
# # # # # # # # # #
#  K i k o f r i  #
# # # # # # # # # #

# Basic
name: "K i k o f r i"
description: "dirty and malnourished jekyll theme"
author: "kxxvii"
title: "Kikofri"

# URL
url: "https://github.com/kxxvii/Kikofri"
baseurl: ""
permalink: /:year/:month/:day/:title.html

# Markdown
markdown: kramdown

# Navigation
nav:
 - name: "about"
   href: "/about"

 - name: "tags"
   href: "/tags"

 - name: "contact"
   href: "/mailto:ivantheterrible@1530to1584.gov"

# Sass
sass:
 style: compressed

# Excerpt
excerpt_separator: <!-ex->

#Gems
plugins:
    - liquid

# Scopes
defaults:
 -
  scope:
   path: ""
   type: "posts"
  values:
   layout: "post"
---
