# # # # # # # # # #
#  K i k o f r i  #
# # # # # # # # # #

# # # # #
# Used as meta-data for 'head.html' among 
# other things.
#
# Basic, either your jekyll site's name or
# an organization.
name: "Ink Machine"
description: ""

# This should be a person of some sort.
author: "Mo Varnez"

# Would make sense to use the 'name:' above
# here. This is an alternative title.
title: "The Ink Machine"

# 'en_US' is the default language. Enter a
# new default language here. Making 'en_US'
# an alternative language. See 'head.html'
lang: es_ES

# Default post and page image if it's those
# are unspecified.
image: https://avatars.githubusercontent.com/u/78277943?

# I just set this to whatever the above
# image value is.
# Could be some other image though.
logo: https://avatars.githubusercontent.com/u/78277943?
#
# # # # #

# URL-stuff, don't forget the 'http...'-part
url: "https://movarnez.github.io"
#baseurl: ""
permalink: /:year/:month/:day/:title.html

# Markdown
markdown: kramdown

# Navigation
nav:
 - name: "about"
   href: "/about"

 - name: "tags"
   href: "/tags"

 - name: "feed"
   href: "/feed.xml"

 - name: "contact"
   href: "/mailto:amartinez.olivaw@gmail.com"
